
outline = ['Building ', 'District ', 'Unlocked with ', 'Era ',]

buildings = [

    'Hangar (Civ6) Hangar	Aerodrome	Flight	Modern Era',
    'Airport (Civ6) Airport	Aerodrome	Advanced Flight	Atomic Era',
    'Madrasa (Civ6) Madrasa',
    '(Arabia)	Campus	Theology	Classical Era',
    'University (Civ6) University	Campus	Education	Medieval Era',
    'Library (Civ6) Library	Campus	Writing	Ancient Era',
    'Research Lab (Civ6) Research Lab	Campus	Chemistry	Modern Era',
    'Palace (Civ6) Palace	City Center	Empire Capital6 Capital	None',
    'Monument (Civ6) Monument	City Center	None	Ancient Era',
    'Medieval Walls (Civ6) Medieval Walls	City Center	Castles	Medieval Era',
    'Water Mill (Civ6) Water Mill	City Center	Wheel	Ancient Era',
    'Ancient Walls (Civ6) Ancient Walls	City Center	Masonry	Ancient Era',
    'Granary (Civ6) Granary	City Center	Pottery	Ancient Era',
    'Sewer (Civ6) Sewer	City Center	Sanitation	Industrial Era',
    'Tsikhe (Civ6) Tsikhe R&amp;F-Only',
    '(Georgia)	City Center	Siege Tactics	Renaissance Era',
    'Renaissance Walls (Civ6) Renaissance Walls	City Center	Siege Tactics	Renaissance Era',
    'Flood Barrier (Civ6) Flood Barrier GS-Only	City Center	Computers	Atomic Era',
    'Market (Civ6) Market	Commercial Hub	Currency	Classical Era',
    'Sukiennice (Civ6) Sukiennice',
    '(Poland)	Commercial Hub	Currency	Classical Era',
    'Stock Exchange (Civ6) Stock Exchange	Commercial Hub	Economics	Industrial Era',
    'Bank (Civ6) Bank	Commercial Hub	Banking	Renaissance Era',
    'Grand Bazaar (Civ6) Grand Bazaar GS-Only',
    '(Ottomans)	Commercial Hub	Banking	Renaissance Era',
    'Hydroelectric Dam (Civ6) Hydroelectric Dam GS-Only	Dam	Electricity	Modern Era',
    'Armory (Civ6) Armory	Encampment	Military Engineering	Medieval Era',
    'Basilikoi Paides (Civ6) Basilikoi Paides',
    '(Macedon)	Encampment	Bronze Working	Ancient Era',
    'Barracks (Civ6) Barracks	Encampment	Bronze Working	Ancient Era',
    'Ordu (Civ6) Ordu R&amp;F-Only',
    '(Mongolia)	Encampment	Horseback Riding	Classical Era',
    'Stable (Civ6) Stable	Encampment	Horseback Riding	Classical Era',
    'Military Academy (Civ6) Military Academy	Encampment	Military Science	Industrial Era',
    'Tlachtli (Civ6) Tlachtli',
    '(Aztec)	Entertainment Complex	Games and Recreation	Classical Era',
    'Arena (Civ6) Arena	Entertainment Complex	Games and Recreation	Classical Era',
    'Zoo (Civ6) Zoo	Entertainment Complex	Natural History	Industrial Era',
    'Thermal Bath (Civ6) Thermal Bath GS-Only',
    '(Hungary)	Entertainment Complex	Natural History	Industrial Era',
    'Stadium (Civ6) Stadium	Entertainment Complex	Professional Sports	Atomic Era',
    'Ancestral Hall (Civ6) Ancestral Hall R&amp;F-Only	Government Plaza R&amp;F-Only	Autocracy, Classical Republic, or Oligarchy	Classical Era',
    'Audience Chamber (Civ6) Audience Chamber R&amp;F-Only	Government Plaza R&amp;F-Only	Autocracy, Classical Republic, or Oligarchy	Classical Era',
    'Warlord&#039;s Throne (Civ6) Warlord's Throne R&amp;F-Only	Government Plaza R&amp;F-Only	Autocracy, Classical Republic, or Oligarchy	Classical Era',
    'Intelligence Agency (Civ6) Intelligence Agency R&amp;F-Only	Government Plaza R&amp;F-Only	Merchant Republic, Monarchy, or Theocracy	Medieval Era/Renaissance Era',
    'Queen&#039;s Bibliotheque (Civ6) Queen's Bibliotheque GS-Only',
    '(Kristina)	Government Plaza R&amp;F-Only	Monarchy, Merchant Republic or Theocracy	Medieval Era',
    'Grand Master&#039;s Chapel (Civ6) Grand Master's Chapel R&amp;F-Only	Government Plaza R&amp;F-Only	Merchant Republic, Monarchy, or Theocracy	Medieval Era/Renaissance Era',
    'Foreign Ministry (Civ6) Foreign Ministry R&amp;F-Only	Government Plaza R&amp;F-Only	Merchant Republic, Monarchy, or Theocracy	Medieval Era/Renaissance Era',
    'National History Museum (Civ6) National History Museum R&amp;F-Only	Government Plaza R&amp;F-Only	Communism, Democracy, or Fascism	Modern Era',
    'Royal Society (Civ6) Royal Society R&amp;F-Only	Government Plaza R&amp;F-Only	Communism, Democracy, or Fascism	Modern Era',
    'War Department (Civ6) War Department R&amp;F-Only	Government Plaza R&amp;F-Only	Communism, Democracy, or Fascism	Modern Era',
    'Lighthouse (Civ6) Lighthouse	Harbor	Celestial Navigation	Classical Era',
    'Shipyard (Civ6) Shipyard	Harbor	Mass Production	Renaissance Era',
    'Seaport (Civ6) Seaport	Harbor	Electricity	Modern Era',
    'Mosque (Civ6) Mosque	Holy Site	Religious Belief	None',
    'Pagoda (Civ6) Pagoda	Holy Site	Religious Belief	None',
    'Stupa (Civ6) Stupa	Holy Site	Religious Belief	None',
    'Synagogue (Civ6) Synagogue	Holy Site	Religious Belief	None',
    'Wat (Civ6) Wat	Holy Site	Religious Belief	None',
    'Prasat (Civ6) Prasat',
    '(Khmer)	Holy Site	Theology	Classical Era',
    'Stave Church (Civ6) Stave Church',
    '(Norway)	Holy Site	Theology	Classical Era',
    'Cathedral (Civ6) Cathedral	Holy Site	Religious Belief	None',
    'Dar-e Mehr (Civ6) Dar-e Mehr	Holy Site	Religious Belief	None',
    'Meeting House (Civ6) Meeting House	Holy Site	Religious Belief	None',
    'Gurdwara (Civ6) Gurdwara	Holy Site	Religious Belief	None',
    'Shrine (Civ6) Shrine	Holy Site	Astrology	Ancient Era',
    'Temple (Civ6) Temple	Holy Site	Theology	Classical Era',
    'Workshop (Civ6) Workshop	Industrial Zone	Apprenticeship	Medieval Era',
    'Factory (Civ6) Factory	Industrial Zone	Industrialization	Industrial Era',
    'Electronics Factory (Civ6) Electronics Factory',
    '(Japan)	Industrial Zone	Industrialization	Industrial Era',
    'Oil Power Plant (Civ6) Oil Power Plant GS-Only	Industrial Zone	Electricity	Modern Era',
    'Coal Power Plant (Civ6) Coal Power Plant GS-Only	Industrial Zone	Industrialization	Industrial Era',
    'Power Plant (Civ6) Power Plant (Vanilla and R&amp;F-Only only)	Industrial Zone	Electricity	Modern Era',
    'Nuclear Power Plant (Civ6) Nuclear Power Plant GS-Only	Industrial Zone	Nuclear Fission	Atomic Era',
    'Shopping Mall (Civ6) Shopping Mall R&amp;F-Only	Neighborhood	Capitalism	Modern Era',
    'Food Market (Civ6) Food Market R&amp;F-Only	Neighborhood	Replaceable Parts	Modern Era',
    'Amphitheater (Civ6) Amphitheater	Theater Square	Drama and Poetry	Classical Era',
    'Marae (Civ6) Marae GS-Only',
    '(Māori)	Theater Square	Drama and Poetry	Classical Era',
    'Art Museum (Civ6) Art Museum	Theater Square	Humanism	Renaissance Era',
    'Archaeological Museum (Civ6) Archaeological Museum	Theater Square	Humanism	Renaissance Era',
    'Film Studio (Civ6) Film Studio',
    '(America)	Theater Square	Radio	Modern Era',
    'Broadcast Center (Civ6) Broadcast Center	Theater Square	Radio	Modern Era',
    'Aquarium (Civ6) Aquarium R&amp;F-Only	Water Park R&amp;F-Only	Natural History	Industrial Era',
    'Ferris Wheel (Civ6) Ferris Wheel R&amp;F-Only	Water Park R&amp;F-Only	Natural History	Industrial Era',
    'Aquatics Center (Civ6) Aquatics Center R&amp;F-Only	Water Park R&amp;F-Only	Professional Sports	Atomic Era',
]