version: '3'

services:
    backend:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        image: civ_backend_dev
        # command: sh
        command: uvicorn backend_main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            # - 8000:8000
            - 8314:8000
        environment:
            - ENVIRONMENT=dev
            - SERVICE=backend
            - MONGOENV=reg

    # calculator:
    #     build:
    #         context: .
    #         dockerfile: calculator/Dockerfile
    #     image: civ_calculator
    #     command: sh
    #     # command: uvicorn backend:app --reload --host 0.0.0.0 --port 8000
    #     volumes:
    #         - .:/usr/src
    #     ports:
    #         - 8316:8000
    #     environment:
    #         - ENVIRONMENT=dev
    #         - SERVICE=calculator

    # database:
    #     image: mongo
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: example

    # database:
    #     image: mongo:latest
    #     environment: 
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: rootpassword
    #     ports:
    #         # - 8305:8000
    #         - 27017:27017
    #         - 27018:27018
    #         - 27019:27019
    #     volumes:
    #         - ./db:/data/db
    #         # - mongodb_data_container:/data/db
    #     # docker run -it -v ${MONGODB_DIR}:/data/db -p ${MONGODB_PORT}:27017 --name mongodb-${1} -d mongo
        
    #     # docker run -d -p 27017-27019:27017-27019 --name mongodb mongo
    #     # docker exec -it mongodb bash
    #         # mongo


    # database:
    #     # image: mongo
    #     build:
    #         context: .
    #     volumes:
    #         - ./mongo-data:/data/db
    #         - ./mongo-app:/var/www/html
    #     ports:
    #         - 27017:27017
    #     environment: 
    #         - MONGO_INITDB_ROOT_USERNAME=root
    #         - MONGO_INITDB_ROOT_PASSWORD=password


    # bash:
    #     build: 
    #         context: .
    #         dockerfile: features/Dockerfile
    #     image: civ_bash
    #     # command: sh; pytest -h
    #     command: bash
    #     volumes:
    #         - .:/usr/src
    #     ports:
    #         - 8023:8000
    #     environment:
    #         - ENVIRONMENT=test
    #         - SERVICE=bash
    #         - MONGOENV=reg

    bash:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_bash
        command: bash
        volumes:
            - .:/usr/src
        ports:
            - 8023:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=bash
            - MONGOENV=reg

volumes:
    mongodb_data_container:


