version: '3'

services:
    backend:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        image: civ_backend_regs
        restart: always
        # command: uvicorn backend:app --workers 1 --host 0.0.0.0 --port 8000
        command: uvicorn backend_main:app --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8204:8000
        environment:
            - ENVIRONMENT=reg
            - SERVICE=backend
        container_name: civ_vi_reg_backend

    # calculator:
    #     build:
    #         context: .
    #         dockerfile: calculator/Dockerfile
    #     image: civ_calculator
    #     restart: always
    #     command: uvicorn calculator:app --host 0.0.0.0 --port 8000
    #     volumes:
    #         - .:/usr/src
    #     ports:
    #       - 8205:8000
    #     environment:
    #         - ENVIRONMENT=reg
    #         - SERVICE=calculator
