version: '3'

services:
    backend:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        image: civ_backend
        restart: always
        command: uvicorn backend:app --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8104:8000
        environment:
            - ENVIRONMENT=prod
            - SERVICE=backend

    calculator:
        build:
            context: .
            dockerfile: backend/Dockerfile
        image: civ_calculator
        restart: always
        command: uvicorn calculator:app --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
          - 8105:8000
        environment:
            - ENVIRONMENT=prod
            - SERVICE=calculator
