version: '3'

services:
    backend:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        image: civ_backend_dev
        # command: sh
        command: uvicorn backend_main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            # - 8000:8000
            - 8314:8000
        environment:
            - ENVIRONMENT=dev
            - SERVICE=backend

    # calculator:
    #     build:
    #         context: .
    #         dockerfile: calculator/Dockerfile
    #     image: civ_calculator
    #     command: sh
    #     # command: uvicorn backend:app --reload --host 0.0.0.0 --port 8000
    #     volumes:
    #         - .:/usr/src
    #     ports:
    #         - 8316:8000
    #     environment:
    #         - ENVIRONMENT=dev
    #         - SERVICE=calculator

    database:
        image: mongo:latest
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 8305:8000
        volumes:
            - ./db:/data/db
            # - mongodb_data_container:/data/db
        # docker run -it -v ${MONGODB_DIR}:/data/db -p ${MONGODB_PORT}:27017 --name mongodb-${1} -d mongo

    bash:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_bash
        # command: sh; pytest -h
        command: bash
        volumes:
            - .:/usr/src
        ports:
            - 8023:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=bash

volumes:
    mongodb_data_container:


