version: '3'

services:
    functional:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_functional
        # command: behave features/data_validator.feature
        # command: behave features/main.feature:6
        # command: behave --tags="@owma"
        command: behave
        volumes:
            - .:/usr/src
        ports:
            - 8020:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=functional

    unit:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_unit
        command: pytest --cov-report html
        # command: pytest --cov=. .
        # command: pytest --cov=. tests/test_data_validator.py
        # command: pytest --cov=. tests/test_application.py
        volumes:
            - .:/usr/src
        ports:
            - 8021:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=unit

    coverage:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_unit
        command: pytest
        volumes:
            - .:/usr/src
        ports:
            - 8021:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=unit

    lint:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_lint
        # command: sh
        command: pycodestyle --show-source
        # command: pycodestyle --show-source --benchmark
        # command: pycodestyle dev_tools/main_tool.py --show-source
        # command: pycodestyle dev_tools/main_tool.py --show-source --show-pep8
        volumes:
            - .:/usr/src
        ports:
            - 8022:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=lint

    bash:
        build: 
            context: .
            dockerfile: features/Dockerfile
        image: civ_bash
        command: bash
        volumes:
            - .:/usr/src
        ports:
            - 8023:8000
        environment:
            - ENVIRONMENT=test
            - SERVICE=lint
