version: '3'

services:
    backend:
        build: 
            context: .
            dockerfile: backend/Dockerfile
        image: civ_backend
        restart: always
        command: uvicorn backend:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8304:8000
        environment:
            - ENVIRONMENT=dev
            - SERVICE=backend

    calculator:
        build:
            context: .
            dockerfile: calculator/Dockerfile
        image: civ_calculator
        restart: always
        command: uvicorn backend:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
          - 8305:8000
        environment:
            - ENVIRONMENT=dev
            - SERVICE=calculator
