version: '3'

services:

    frontend:
        build: .
        image: civ_fe
        restart: always
        command: uvicorn frontend:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8100:8000

        environment:
            - ENVIRONMENT=prod
            - TESTING=False

    backend:
        build: .
        image: civ_be
        restart: always
        command: uvicorn backend:app --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8101:8000

        environment:
            - ENVIRONMENT=prod
            - TESTING=False

    dev-fe:
        build: .
        image: civ_dev_fe
        command: uvicorn frontend:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8110:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=False

    dev-be:
        build: .
        image: civ_dev_be
        command: uvicorn backend:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8120:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=False

    test:
        build: .
        image: civ_testing
        command: behave
        volumes:
            - .:/usr/src
        ports:
            - 8130:8000
        environment:
            - ENVIRONMENT=test
            - TESTING=True

    unit-test:
        build: .
        image: civ_unit_testing
        command: pytest
        volumes:
            - .:/usr/src
        ports:
            - 8140:8000
        environment:
            - ENVIRONMENT=test
            - TESTING=True
