openapi: 3.0.0
info:
    title: Civ VI City Planner
    description: Optomize your civ vi city plans
    version: 0.1.0

servers:
    - url: http://0.0.0.0
      description: For now im just testing on localhost

paths:
    /city_plan:
        get:
            summary: Returns the optimal city layout
            operationId: GetCityPlan
            parameters:
                - in: path
                  name: cityID
                  required: true
                  description: uuid for the city
                  schema:
                    type: string
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/City'
                '400':
                    description: cityid not found in database
                # '401': NOT MVP
                #     description: user is not allowed to view this city
                '418':
                    description: I'm a teapot
        post:
            summary: Update a city
            operationId: UpdateCityPlan
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/City'
            responses:
                '201':
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/City'
                '406':
                    description: There is a tile missmatch like adding whales to a mountain tile
                    content:
                        application/json:
                            schema:
                                type: object

components:
    schemas:
        City:
            type: object
            properties:
                name:
                    type: string
                tiles:
                    type: object
                    properties:
                        center:
                            type: array
                            items:
                                $ref: '#/components/schemas/Tile'
                        inner:
                            type: array
                            items:
                                $ref: '#/components/schemas/Tile'
                        middle:
                            type: array
                            items:
                                $ref: '#/components/schemas/Tile'
                        outer:
                            type: array
                            items:
                                $ref: '#/components/schemas/Tile'
                        nearby:
                            type: array
                            items:
                                $ref: '#/components/schemas/Tile'
                # locked boolean NOT MVP
                # era: string NOT MVP
                #     enum:
                #         - Era:0 Ancient
                #         - Era:1 Classical
                #         - Era:2 Medieval
                #         - Era:3 Renaissance
                #         - Era:4 Industrial
                #         - Era:5 Modern
                #         - Era:6 Atomic
                #         - Era:7 Information
                #         - Era:8 Future
                # Trader: boolean Trader NOT MVP. eventually whats the other city to calculate trader yield
                # Governer: Governer NOT MVP. eventually what governer and their abilities
                # amenities: string NOT MVP
                # neighbor_power: string NOT MVP

            required:
                # - name # Name might actually be optional in case somebody wants to test out a city but not save it
                - center
                - inner
                - middle
                - outer
                - nearby
        Tile:
            properties:
                terrain:
                    $ref: '#/components/schemas/Terrain'
                feature:
                    $ref: '#/components/schemas/Feature'
                resource:
                    $ref: '#/components/schemas/Resource'
                improvement:
                    $ref: '#/components/schemas/Improvement'
                district:
                    $ref: '#/components/schemas/District'
                # wonder:
                #     $ref: '#/components/schemas/Wonder'
            # required:
                # If i dont find the specific tile elements i will assume empty
        Terrain:
            properties:
                name:
                    $ref: '#/components/schemas/TerrainType'
                hill: 
                    type: boolean
            required:
                - name
        TerrainType:
            type: string
            enum:
                - grassland
                - plains
                - desert
                - tundra
                - snow
                - coast
                - lake
                - ocean
        Feature:
            properties:
                name: 
                    $ref: '#/components/schemas/FeatureType'
                river: 
                    type: boolean
            required:
                - name
        FeatureType:
            type: string
            enum:
                - woods
                - rainforest
                - marsh
                - floodplains
                - oasis
                - mountain
                - cliffs
                - reef
                - ice
                - cataract
                - volcano
                - volcanic_soil
                - geothermal
        Resource:
            type: string
            enum:
                - bananas
                - copper
                - cattle
                - crabs
                - deer
                - fish
                - maize
                - rice
                - sheep
                - stone
                - wheat
                - amber
                - cinnamon
                - citrus
                - cloves
                - cocoa
                - coffee
                - cosmetics
                - cotton
                - dyes
                - diamonds
                - furs
                - gold_ore
                - gypsum
                - honey
                - insense
                - ivory
                - jade
                - jeans
                - marble
                - murcury
                - olives
                - pearls
                - perfume
                - salt
                - silk
                - silver
                - spices
                - sugar
                - tea
                - tobacco
                - toys
                - truffles
                - turtles
                - whales
                - wine
                - horses
                - iron
                - niter
                - coal
                - oil
                - aluminum
                - uranium
        Improvement:
            type: string
            enum:
                - farm
                - mine
                - quarry
                - plantation
                - camp
                - pasture
                - fishing_boats
                - lumber_mill
                - fort
                - airstrip
                - seaside_resort
                - geothermal_plant
                - wind_farm
                - solar_farm
                - offshore_wind_farm
                - ski_resort
                - oil_well
                - offshore_oil_well
                - missle_silo
                - mountain_tunnel
                - railroad
                - seastead
                - alcazar
                - batey
                - cahokia_mounds
                - colossal_heads
                - mahavihara
                - moai
                - monistary
                - nazca_line
                - trading_dome
                - chateau
                - chemamull
                - golf_course
                - great_wall
                - hacienda
                - ice_hocky_rink
                - kampung
                - kurgan
                - mekewap
                - mission
                - nubian_pyramid
                - open_air_museum
                - outback_station
                - pa
                - pairirdaeza
                - polder
                - qhapaq_nan
                - rock_hewn_church
                - roman_fort
                - sphinx
                - stepwell
                - terrace_farms
                - ziggurat
                - city_park
                - fishery
        District:
            properties:
                name:
                    type: string
                buildings:
                    oneOf:
                      - $ref: '#/components/schemas/CityCenter'
                      - $ref: '#/components/schemas/Campus'
                powered: 
                    type: boolean
            required:
                - name
        DistrictBuildings:
            type: object
            required:
                - name
            properties:
                name:
                    type: string
            discriminator:
                propertyName: name
        CityCenter:
            allOf:
              - $ref: '#/components/schemas/DistrictBuildings'
              - type: object
                properties:
                    buildings:
                        type: array
                        items:
                            enum:
                                - granary
                                - monument
                                - water_mill
                                - sewer
        Campus:
            allOf:
              - $ref: '#/components/schemas/DistrictBuildings'
              - type: object
                properties:
                    buildings:
                        type: array
                        items:
                            enum:
                                - library
                                - university
                                - research_lab
                # theater_square:
                #     amphitheater
                #     art_museum
                #     archaeological_museum
                #     broadcast_center
                # holy_site:
                #     shrine
                #     temple
                #     # worship buildings NOT MVP
                # encampment:
                #     barracks
                #     stable
                #     armory
                #     military_academy
                # commercial_hub:
                #     market
                #     bank
                #     stock_exchange
                # harbor:
                #     lighthouse
                #     shipyard
                #     seaport
                # industrial_zone:
                #     workshop
                #     factory
                #     coal_power_plant
                #     oil_power_plant
                #     nuclear_power_plant
                # entertainment_complex:
                #     arena
                #     zoo
                #     stadium
                # water_park:
                #     ferris_wheel
                #     aquarium
                #     aquatics_center
                # aqueduct:
                # neighborhood:
                #     food_market
                #     shopping_mall
                # canal:
                # dam:
                #     hydroelectric_dam
                # aerodrome:
                #     hanger
                #     airport
                # spaceport:
                # govermment_plaza:
                #     ancestral_hall
                #     audience_chamber
                #     warlords_throne
                #     foreign_ministry
                #     grand_masters_chapel
                #     intelligence_agency
                #     queens_bibliotheque
                #     national_history_museum
                #     royal_society
                #     war_department
                # diplomatic_quarter:
                #     consulate
                #     chancery
        # Wonder: NOT MVP
        #     properties:
        #         name: string
        #     required:
        #         - name
        #     enum:
