from .cataract import Cataract
from .cliffs import Cliffs
from .floodplains import Floodplains
from .geothermal_fissure import GeothermalFissure
from .ice import Ice
from .impact_zone import ImpactZone
from .marsh import Marsh
from .mountain import Mountain
from .oasis import Oasis
from .rainforest import Rainforest
from .reef import Reef
from .river import River
from .volcanic_soil import VolcanicSoil
from .volcano import Volcano
from .woods import Woods
