/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AerodomeAllOf
 */
export interface AerodomeAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof AerodomeAllOf
     */
    buildings?: Array<AerodomeAllOfBuildingsEnum>;
}

export function AerodomeAllOfFromJSON(json: any): AerodomeAllOf {
    return AerodomeAllOfFromJSONTyped(json, false);
}

export function AerodomeAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AerodomeAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function AerodomeAllOfToJSON(value?: AerodomeAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum AerodomeAllOfBuildingsEnum {
    Hanger = 'hanger'
}


