/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AerodomeAllOf,
    AerodomeAllOfFromJSON,
    AerodomeAllOfFromJSONTyped,
    AerodomeAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface Aerodome
 */
export interface Aerodome extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Aerodome
     */
    buildings?: Array<AerodomeBuildingsEnum>;
}

export function AerodomeFromJSON(json: any): Aerodome {
    return AerodomeFromJSONTyped(json, false);
}

export function AerodomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aerodome {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function AerodomeToJSON(value?: Aerodome | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum AerodomeBuildingsEnum {
    Hanger = 'hanger'
}


