/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AqueductAllOf
 */
export interface AqueductAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof AqueductAllOf
     */
    buildings?: Array<string>;
}

export function AqueductAllOfFromJSON(json: any): AqueductAllOf {
    return AqueductAllOfFromJSONTyped(json, false);
}

export function AqueductAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AqueductAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function AqueductAllOfToJSON(value?: AqueductAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}


