/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampusAllOf
 */
export interface CampusAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof CampusAllOf
     */
    buildings?: Array<CampusAllOfBuildingsEnum>;
}

export function CampusAllOfFromJSON(json: any): CampusAllOf {
    return CampusAllOfFromJSONTyped(json, false);
}

export function CampusAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampusAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CampusAllOfToJSON(value?: CampusAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum CampusAllOfBuildingsEnum {
    Library = 'library',
    University = 'university',
    ResearchLab = 'research_lab'
}


