/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AqueductAllOf,
    AqueductAllOfFromJSON,
    AqueductAllOfFromJSONTyped,
    AqueductAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface Canal
 */
export interface Canal extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Canal
     */
    buildings?: Array<string>;
}

export function CanalFromJSON(json: any): Canal {
    return CanalFromJSONTyped(json, false);
}

export function CanalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Canal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CanalToJSON(value?: Canal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}


