/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CityCenterAllOf,
    CityCenterAllOfFromJSON,
    CityCenterAllOfFromJSONTyped,
    CityCenterAllOfToJSON,
    DistrictBuildings,
    DistrictBuildingsFromJSON,
    DistrictBuildingsFromJSONTyped,
    DistrictBuildingsToJSON,
} from './';

/**
 * 
 * @export
 * @interface CityCenter
 */
export interface CityCenter extends DistrictBuildings {
    /**
     * 
     * @type {Array<string>}
     * @memberof CityCenter
     */
    buildings?: Array<CityCenterBuildingsEnum>;
}

export function CityCenterFromJSON(json: any): CityCenter {
    return CityCenterFromJSONTyped(json, false);
}

export function CityCenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityCenter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictBuildingsFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CityCenterToJSON(value?: CityCenter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictBuildingsToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum CityCenterBuildingsEnum {
    Granary = 'granary',
    Monument = 'monument',
    WaterMill = 'water_mill',
    Sewer = 'sewer'
}


