/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityCenterAllOf
 */
export interface CityCenterAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof CityCenterAllOf
     */
    buildings?: Array<CityCenterAllOfBuildingsEnum>;
}

export function CityCenterAllOfFromJSON(json: any): CityCenterAllOf {
    return CityCenterAllOfFromJSONTyped(json, false);
}

export function CityCenterAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityCenterAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CityCenterAllOfToJSON(value?: CityCenterAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum CityCenterAllOfBuildingsEnum {
    Granary = 'granary',
    Monument = 'monument',
    WaterMill = 'water_mill',
    Sewer = 'sewer'
}


