/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommercialHubAllOf
 */
export interface CommercialHubAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommercialHubAllOf
     */
    buildings?: Array<CommercialHubAllOfBuildingsEnum>;
}

export function CommercialHubAllOfFromJSON(json: any): CommercialHubAllOf {
    return CommercialHubAllOfFromJSONTyped(json, false);
}

export function CommercialHubAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialHubAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CommercialHubAllOfToJSON(value?: CommercialHubAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum CommercialHubAllOfBuildingsEnum {
    Market = 'market',
    Bank = 'bank',
    StockExchange = 'stock_exchange'
}


