/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommercialHubAllOf,
    CommercialHubAllOfFromJSON,
    CommercialHubAllOfFromJSONTyped,
    CommercialHubAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommercialHub
 */
export interface CommercialHub extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommercialHub
     */
    buildings?: Array<CommercialHubBuildingsEnum>;
}

export function CommercialHubFromJSON(json: any): CommercialHub {
    return CommercialHubFromJSONTyped(json, false);
}

export function CommercialHubFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommercialHub {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function CommercialHubToJSON(value?: CommercialHub | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum CommercialHubBuildingsEnum {
    Market = 'market',
    Bank = 'bank',
    StockExchange = 'stock_exchange'
}


