/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DamAllOf,
    DamAllOfFromJSON,
    DamAllOfFromJSONTyped,
    DamAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface Dam
 */
export interface Dam extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Dam
     */
    buildings?: Array<DamBuildingsEnum>;
}

export function DamFromJSON(json: any): Dam {
    return DamFromJSONTyped(json, false);
}

export function DamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function DamToJSON(value?: Dam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum DamBuildingsEnum {
    HydroelectricDam = 'hydroelectric_dam'
}


