/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DamAllOf
 */
export interface DamAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof DamAllOf
     */
    buildings?: Array<DamAllOfBuildingsEnum>;
}

export function DamAllOfFromJSON(json: any): DamAllOf {
    return DamAllOfFromJSONTyped(json, false);
}

export function DamAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DamAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function DamAllOfToJSON(value?: DamAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum DamAllOfBuildingsEnum {
    HydroelectricDam = 'hydroelectric_dam'
}


