/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiplomaticQuarterAllOf
 */
export interface DiplomaticQuarterAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof DiplomaticQuarterAllOf
     */
    buildings?: Array<DiplomaticQuarterAllOfBuildingsEnum>;
}

export function DiplomaticQuarterAllOfFromJSON(json: any): DiplomaticQuarterAllOf {
    return DiplomaticQuarterAllOfFromJSONTyped(json, false);
}

export function DiplomaticQuarterAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiplomaticQuarterAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function DiplomaticQuarterAllOfToJSON(value?: DiplomaticQuarterAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum DiplomaticQuarterAllOfBuildingsEnum {
    Consulate = 'consulate',
    Chancery = 'chancery'
}


