/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiplomaticQuarterAllOf,
    DiplomaticQuarterAllOfFromJSON,
    DiplomaticQuarterAllOfFromJSONTyped,
    DiplomaticQuarterAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiplomaticQuarter
 */
export interface DiplomaticQuarter extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof DiplomaticQuarter
     */
    buildings?: Array<DiplomaticQuarterBuildingsEnum>;
}

export function DiplomaticQuarterFromJSON(json: any): DiplomaticQuarter {
    return DiplomaticQuarterFromJSONTyped(json, false);
}

export function DiplomaticQuarterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiplomaticQuarter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function DiplomaticQuarterToJSON(value?: DiplomaticQuarter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum DiplomaticQuarterBuildingsEnum {
    Consulate = 'consulate',
    Chancery = 'chancery'
}


