/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Campus,
    CampusFromJSON,
    CampusFromJSONTyped,
    CampusToJSON,
    CityCenter,
    CityCenterFromJSON,
    CityCenterFromJSONTyped,
    CityCenterToJSON,
} from './';

/**
 * 
 * @export
 * @interface District
 */
export interface District {
    /**
     * 
     * @type {string}
     * @memberof District
     */
    name: string;
    /**
     * 
     * @type {CityCenter | Campus}
     * @memberof District
     */
    buildings?: CityCenter | Campus;
    /**
     * 
     * @type {boolean}
     * @memberof District
     */
    powered?: boolean;
}

export function DistrictFromJSON(json: any): District {
    return DistrictFromJSONTyped(json, false);
}

export function DistrictFromJSONTyped(json: any, ignoreDiscriminator: boolean): District {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'buildings': !exists(json, 'buildings') ? undefined : CityCenter | CampusFromJSON(json['buildings']),
        'powered': !exists(json, 'powered') ? undefined : json['powered'],
    };
}

export function DistrictToJSON(value?: District | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'buildings': CityCenter | CampusToJSON(value.buildings),
        'powered': value.powered,
    };
}


