/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     CityCenterFromJSONTyped,
     CampusFromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface DistrictBuildings
 */
export interface DistrictBuildings {
    /**
     * 
     * @type {string}
     * @memberof DistrictBuildings
     */
    name: string;
}

export function DistrictBuildingsFromJSON(json: any): DistrictBuildings {
    return DistrictBuildingsFromJSONTyped(json, false);
}

export function DistrictBuildingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistrictBuildings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['name'] === 'CityCenter') {
            return CityCenterFromJSONTyped(json, true);
        }
        if (json['name'] === 'Campus') {
            return CampusFromJSONTyped(json, true);
        }
    }
    return {
        
        'name': json['name'],
    };
}

export function DistrictBuildingsToJSON(value?: DistrictBuildings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


