/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    EncampmentAllOf,
    EncampmentAllOfFromJSON,
    EncampmentAllOfFromJSONTyped,
    EncampmentAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface Encampment
 */
export interface Encampment extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Encampment
     */
    buildings?: Array<EncampmentBuildingsEnum>;
}

export function EncampmentFromJSON(json: any): Encampment {
    return EncampmentFromJSONTyped(json, false);
}

export function EncampmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Encampment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function EncampmentToJSON(value?: Encampment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum EncampmentBuildingsEnum {
    Barracks = 'barracks',
    Stable = 'stable',
    Armory = 'armory',
    MilitaryAcademy = 'military_academy'
}


