/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncampmentAllOf
 */
export interface EncampmentAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof EncampmentAllOf
     */
    buildings?: Array<EncampmentAllOfBuildingsEnum>;
}

export function EncampmentAllOfFromJSON(json: any): EncampmentAllOf {
    return EncampmentAllOfFromJSONTyped(json, false);
}

export function EncampmentAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncampmentAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function EncampmentAllOfToJSON(value?: EncampmentAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum EncampmentAllOfBuildingsEnum {
    Barracks = 'barracks',
    Stable = 'stable',
    Armory = 'armory',
    MilitaryAcademy = 'military_academy'
}


