/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntertainmentComplexAllOf
 */
export interface EntertainmentComplexAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof EntertainmentComplexAllOf
     */
    buildings?: Array<EntertainmentComplexAllOfBuildingsEnum>;
}

export function EntertainmentComplexAllOfFromJSON(json: any): EntertainmentComplexAllOf {
    return EntertainmentComplexAllOfFromJSONTyped(json, false);
}

export function EntertainmentComplexAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntertainmentComplexAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function EntertainmentComplexAllOfToJSON(value?: EntertainmentComplexAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum EntertainmentComplexAllOfBuildingsEnum {
    Arena = 'arena',
    Zoo = 'zoo',
    Stadium = 'stadium'
}


