/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    EntertainmentComplexAllOf,
    EntertainmentComplexAllOfFromJSON,
    EntertainmentComplexAllOfFromJSONTyped,
    EntertainmentComplexAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntertainmentComplex
 */
export interface EntertainmentComplex extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof EntertainmentComplex
     */
    buildings?: Array<EntertainmentComplexBuildingsEnum>;
}

export function EntertainmentComplexFromJSON(json: any): EntertainmentComplex {
    return EntertainmentComplexFromJSONTyped(json, false);
}

export function EntertainmentComplexFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntertainmentComplex {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function EntertainmentComplexToJSON(value?: EntertainmentComplex | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum EntertainmentComplexBuildingsEnum {
    Arena = 'arena',
    Zoo = 'zoo',
    Stadium = 'stadium'
}


