/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeatureType,
    FeatureTypeFromJSON,
    FeatureTypeFromJSONTyped,
    FeatureTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Feature
 */
export interface Feature {
    /**
     * 
     * @type {FeatureType}
     * @memberof Feature
     */
    name: FeatureType;
    /**
     * 
     * @type {boolean}
     * @memberof Feature
     */
    river?: boolean;
}

export function FeatureFromJSON(json: any): Feature {
    return FeatureFromJSONTyped(json, false);
}

export function FeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': FeatureTypeFromJSON(json['name']),
        'river': !exists(json, 'river') ? undefined : json['river'],
    };
}

export function FeatureToJSON(value?: Feature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': FeatureTypeToJSON(value.name),
        'river': value.river,
    };
}


