/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FeatureType {
    Woods = 'woods',
    Rainforest = 'rainforest',
    Marsh = 'marsh',
    Floodplains = 'floodplains',
    Oasis = 'oasis',
    Mountain = 'mountain',
    Cliffs = 'cliffs',
    Reef = 'reef',
    Ice = 'ice',
    Cataract = 'cataract',
    Volcano = 'volcano',
    VolcanicSoil = 'volcanic_soil',
    Geothermal = 'geothermal'
}

export function FeatureTypeFromJSON(json: any): FeatureType {
    return FeatureTypeFromJSONTyped(json, false);
}

export function FeatureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureType {
    return json as FeatureType;
}

export function FeatureTypeToJSON(value?: FeatureType | null): any {
    return value as any;
}

