/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GovernmentPlazaAllOf
 */
export interface GovernmentPlazaAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof GovernmentPlazaAllOf
     */
    buildings?: Array<GovernmentPlazaAllOfBuildingsEnum>;
}

export function GovernmentPlazaAllOfFromJSON(json: any): GovernmentPlazaAllOf {
    return GovernmentPlazaAllOfFromJSONTyped(json, false);
}

export function GovernmentPlazaAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernmentPlazaAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function GovernmentPlazaAllOfToJSON(value?: GovernmentPlazaAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum GovernmentPlazaAllOfBuildingsEnum {
    AncestralHall = 'ancestral_hall',
    AudienceChamber = 'audience_chamber',
    WarlordsThrone = 'warlords_throne',
    ForeignMinistry = 'foreign_ministry',
    GrandMastersChapel = 'grand_masters_chapel',
    IntelligenceAgency = 'intelligence_agency',
    QueensBibliotheque = 'queens_bibliotheque',
    NationalHistoryMuseum = 'national_history_museum',
    RoyalSociety = 'royal_society',
    WarDepartment = 'war_department'
}


