/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    GovernmentPlazaAllOf,
    GovernmentPlazaAllOfFromJSON,
    GovernmentPlazaAllOfFromJSONTyped,
    GovernmentPlazaAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface GovernmentPlaza
 */
export interface GovernmentPlaza extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof GovernmentPlaza
     */
    buildings?: Array<GovernmentPlazaBuildingsEnum>;
}

export function GovernmentPlazaFromJSON(json: any): GovernmentPlaza {
    return GovernmentPlazaFromJSONTyped(json, false);
}

export function GovernmentPlazaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernmentPlaza {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function GovernmentPlazaToJSON(value?: GovernmentPlaza | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum GovernmentPlazaBuildingsEnum {
    AncestralHall = 'ancestral_hall',
    AudienceChamber = 'audience_chamber',
    WarlordsThrone = 'warlords_throne',
    ForeignMinistry = 'foreign_ministry',
    GrandMastersChapel = 'grand_masters_chapel',
    IntelligenceAgency = 'intelligence_agency',
    QueensBibliotheque = 'queens_bibliotheque',
    NationalHistoryMuseum = 'national_history_museum',
    RoyalSociety = 'royal_society',
    WarDepartment = 'war_department'
}


