/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HarborAllOf
 */
export interface HarborAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof HarborAllOf
     */
    buildings?: Array<HarborAllOfBuildingsEnum>;
}

export function HarborAllOfFromJSON(json: any): HarborAllOf {
    return HarborAllOfFromJSONTyped(json, false);
}

export function HarborAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): HarborAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function HarborAllOfToJSON(value?: HarborAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum HarborAllOfBuildingsEnum {
    Lighthouse = 'lighthouse',
    Shipyard = 'shipyard',
    Seaport = 'seaport'
}


