/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HolySiteAllOf
 */
export interface HolySiteAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof HolySiteAllOf
     */
    buildings?: Array<HolySiteAllOfBuildingsEnum>;
}

export function HolySiteAllOfFromJSON(json: any): HolySiteAllOf {
    return HolySiteAllOfFromJSONTyped(json, false);
}

export function HolySiteAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolySiteAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function HolySiteAllOfToJSON(value?: HolySiteAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum HolySiteAllOfBuildingsEnum {
    Shrine = 'shrine',
    Temple = 'temple'
}


