/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    HolySiteAllOf,
    HolySiteAllOfFromJSON,
    HolySiteAllOfFromJSONTyped,
    HolySiteAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface HolySite
 */
export interface HolySite extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof HolySite
     */
    buildings?: Array<HolySiteBuildingsEnum>;
}

export function HolySiteFromJSON(json: any): HolySite {
    return HolySiteFromJSONTyped(json, false);
}

export function HolySiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolySite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function HolySiteToJSON(value?: HolySite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum HolySiteBuildingsEnum {
    Shrine = 'shrine',
    Temple = 'temple'
}


