/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    IndustrialZoneAllOf,
    IndustrialZoneAllOfFromJSON,
    IndustrialZoneAllOfFromJSONTyped,
    IndustrialZoneAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface IndustrialZone
 */
export interface IndustrialZone extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof IndustrialZone
     */
    buildings?: Array<IndustrialZoneBuildingsEnum>;
}

export function IndustrialZoneFromJSON(json: any): IndustrialZone {
    return IndustrialZoneFromJSONTyped(json, false);
}

export function IndustrialZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustrialZone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function IndustrialZoneToJSON(value?: IndustrialZone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum IndustrialZoneBuildingsEnum {
    Workshop = 'workshop',
    Factory = 'factory',
    CoalPowerPlant = 'coal_power_plant',
    OilPowerPlant = 'oil_power_plant',
    NuclearPowerPlant = 'nuclear_power_plant'
}


