/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndustrialZoneAllOf
 */
export interface IndustrialZoneAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof IndustrialZoneAllOf
     */
    buildings?: Array<IndustrialZoneAllOfBuildingsEnum>;
}

export function IndustrialZoneAllOfFromJSON(json: any): IndustrialZoneAllOf {
    return IndustrialZoneAllOfFromJSONTyped(json, false);
}

export function IndustrialZoneAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustrialZoneAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function IndustrialZoneAllOfToJSON(value?: IndustrialZoneAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum IndustrialZoneAllOfBuildingsEnum {
    Workshop = 'workshop',
    Factory = 'factory',
    CoalPowerPlant = 'coal_power_plant',
    OilPowerPlant = 'oil_power_plant',
    NuclearPowerPlant = 'nuclear_power_plant'
}


