/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NeighborhoodAllOf
 */
export interface NeighborhoodAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof NeighborhoodAllOf
     */
    buildings?: Array<NeighborhoodAllOfBuildingsEnum>;
}

export function NeighborhoodAllOfFromJSON(json: any): NeighborhoodAllOf {
    return NeighborhoodAllOfFromJSONTyped(json, false);
}

export function NeighborhoodAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NeighborhoodAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function NeighborhoodAllOfToJSON(value?: NeighborhoodAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum NeighborhoodAllOfBuildingsEnum {
    FoodMarket = 'food_market',
    ShoppingMall = 'shopping_mall'
}


