/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    NeighborhoodAllOf,
    NeighborhoodAllOfFromJSON,
    NeighborhoodAllOfFromJSONTyped,
    NeighborhoodAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface Neighborhood
 */
export interface Neighborhood extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Neighborhood
     */
    buildings?: Array<NeighborhoodBuildingsEnum>;
}

export function NeighborhoodFromJSON(json: any): Neighborhood {
    return NeighborhoodFromJSONTyped(json, false);
}

export function NeighborhoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Neighborhood {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function NeighborhoodToJSON(value?: Neighborhood | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum NeighborhoodBuildingsEnum {
    FoodMarket = 'food_market',
    ShoppingMall = 'shopping_mall'
}


