/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Resource {
    Bananas = 'bananas',
    Copper = 'copper',
    Cattle = 'cattle',
    Crabs = 'crabs',
    Deer = 'deer',
    Fish = 'fish',
    Maize = 'maize',
    Rice = 'rice',
    Sheep = 'sheep',
    Stone = 'stone',
    Wheat = 'wheat',
    Amber = 'amber',
    Cinnamon = 'cinnamon',
    Citrus = 'citrus',
    Cloves = 'cloves',
    Cocoa = 'cocoa',
    Coffee = 'coffee',
    Cosmetics = 'cosmetics',
    Cotton = 'cotton',
    Dyes = 'dyes',
    Diamonds = 'diamonds',
    Furs = 'furs',
    GoldOre = 'gold_ore',
    Gypsum = 'gypsum',
    Honey = 'honey',
    Insense = 'insense',
    Ivory = 'ivory',
    Jade = 'jade',
    Jeans = 'jeans',
    Marble = 'marble',
    Murcury = 'murcury',
    Olives = 'olives',
    Pearls = 'pearls',
    Perfume = 'perfume',
    Salt = 'salt',
    Silk = 'silk',
    Silver = 'silver',
    Spices = 'spices',
    Sugar = 'sugar',
    Tea = 'tea',
    Tobacco = 'tobacco',
    Toys = 'toys',
    Truffles = 'truffles',
    Turtles = 'turtles',
    Whales = 'whales',
    Wine = 'wine',
    Horses = 'horses',
    Iron = 'iron',
    Niter = 'niter',
    Coal = 'coal',
    Oil = 'oil',
    Aluminum = 'aluminum',
    Uranium = 'uranium'
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    return json as Resource;
}

export function ResourceToJSON(value?: Resource | null): any {
    return value as any;
}

