/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AqueductAllOf,
    AqueductAllOfFromJSON,
    AqueductAllOfFromJSONTyped,
    AqueductAllOfToJSON,
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
} from './';

/**
 * 
 * @export
 * @interface Spaceport
 */
export interface Spaceport extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof Spaceport
     */
    buildings?: Array<string>;
}

export function SpaceportFromJSON(json: any): Spaceport {
    return SpaceportFromJSONTyped(json, false);
}

export function SpaceportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Spaceport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function SpaceportToJSON(value?: Spaceport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}


