/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TerrainType {
    Grassland = 'grassland',
    Plains = 'plains',
    Desert = 'desert',
    Tundra = 'tundra',
    Snow = 'snow',
    Coast = 'coast',
    Lake = 'lake',
    Ocean = 'ocean'
}

export function TerrainTypeFromJSON(json: any): TerrainType {
    return TerrainTypeFromJSONTyped(json, false);
}

export function TerrainTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TerrainType {
    return json as TerrainType;
}

export function TerrainTypeToJSON(value?: TerrainType | null): any {
    return value as any;
}

