/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TerrainType,
    TerrainTypeFromJSON,
    TerrainTypeFromJSONTyped,
    TerrainTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Terrain
 */
export interface Terrain {
    /**
     * 
     * @type {TerrainType}
     * @memberof Terrain
     */
    name: TerrainType;
    /**
     * 
     * @type {boolean}
     * @memberof Terrain
     */
    hill?: boolean;
}

export function TerrainFromJSON(json: any): Terrain {
    return TerrainFromJSONTyped(json, false);
}

export function TerrainFromJSONTyped(json: any, ignoreDiscriminator: boolean): Terrain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': TerrainTypeFromJSON(json['name']),
        'hill': !exists(json, 'hill') ? undefined : json['hill'],
    };
}

export function TerrainToJSON(value?: Terrain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': TerrainTypeToJSON(value.name),
        'hill': value.hill,
    };
}


