/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TheaterSquareAllOf
 */
export interface TheaterSquareAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof TheaterSquareAllOf
     */
    buildings?: Array<TheaterSquareAllOfBuildingsEnum>;
}

export function TheaterSquareAllOfFromJSON(json: any): TheaterSquareAllOf {
    return TheaterSquareAllOfFromJSONTyped(json, false);
}

export function TheaterSquareAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TheaterSquareAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function TheaterSquareAllOfToJSON(value?: TheaterSquareAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum TheaterSquareAllOfBuildingsEnum {
    Amphitheater = 'amphitheater',
    ArtMuseum = 'art_museum',
    ArchaeologicalMuseum = 'archaeological_museum',
    BroadcastCenter = 'broadcast_center'
}


