/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    TheaterSquareAllOf,
    TheaterSquareAllOfFromJSON,
    TheaterSquareAllOfFromJSONTyped,
    TheaterSquareAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface TheaterSquare
 */
export interface TheaterSquare extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof TheaterSquare
     */
    buildings?: Array<TheaterSquareBuildingsEnum>;
}

export function TheaterSquareFromJSON(json: any): TheaterSquare {
    return TheaterSquareFromJSONTyped(json, false);
}

export function TheaterSquareFromJSONTyped(json: any, ignoreDiscriminator: boolean): TheaterSquare {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function TheaterSquareToJSON(value?: TheaterSquare | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum TheaterSquareBuildingsEnum {
    Amphitheater = 'amphitheater',
    ArtMuseum = 'art_museum',
    ArchaeologicalMuseum = 'archaeological_museum',
    BroadcastCenter = 'broadcast_center'
}


