/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Aerodome,
    AerodomeFromJSON,
    AerodomeFromJSONTyped,
    AerodomeToJSON,
    Aqueduct,
    AqueductFromJSON,
    AqueductFromJSONTyped,
    AqueductToJSON,
    Campus,
    CampusFromJSON,
    CampusFromJSONTyped,
    CampusToJSON,
    Canal,
    CanalFromJSON,
    CanalFromJSONTyped,
    CanalToJSON,
    CityCenter,
    CityCenterFromJSON,
    CityCenterFromJSONTyped,
    CityCenterToJSON,
    CommercialHub,
    CommercialHubFromJSON,
    CommercialHubFromJSONTyped,
    CommercialHubToJSON,
    Dam,
    DamFromJSON,
    DamFromJSONTyped,
    DamToJSON,
    DiplomaticQuarter,
    DiplomaticQuarterFromJSON,
    DiplomaticQuarterFromJSONTyped,
    DiplomaticQuarterToJSON,
    Encampment,
    EncampmentFromJSON,
    EncampmentFromJSONTyped,
    EncampmentToJSON,
    EntertainmentComplex,
    EntertainmentComplexFromJSON,
    EntertainmentComplexFromJSONTyped,
    EntertainmentComplexToJSON,
    Feature,
    FeatureFromJSON,
    FeatureFromJSONTyped,
    FeatureToJSON,
    GovernmentPlaza,
    GovernmentPlazaFromJSON,
    GovernmentPlazaFromJSONTyped,
    GovernmentPlazaToJSON,
    Harbor,
    HarborFromJSON,
    HarborFromJSONTyped,
    HarborToJSON,
    HolySite,
    HolySiteFromJSON,
    HolySiteFromJSONTyped,
    HolySiteToJSON,
    Improvement,
    ImprovementFromJSON,
    ImprovementFromJSONTyped,
    ImprovementToJSON,
    IndustrialZone,
    IndustrialZoneFromJSON,
    IndustrialZoneFromJSONTyped,
    IndustrialZoneToJSON,
    Neighborhood,
    NeighborhoodFromJSON,
    NeighborhoodFromJSONTyped,
    NeighborhoodToJSON,
    Resource,
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    Spaceport,
    SpaceportFromJSON,
    SpaceportFromJSONTyped,
    SpaceportToJSON,
    Terrain,
    TerrainFromJSON,
    TerrainFromJSONTyped,
    TerrainToJSON,
    TheaterSquare,
    TheaterSquareFromJSON,
    TheaterSquareFromJSONTyped,
    TheaterSquareToJSON,
    WaterPark,
    WaterParkFromJSON,
    WaterParkFromJSONTyped,
    WaterParkToJSON,
} from './';

/**
 * 
 * @export
 * @interface Tile
 */
export interface Tile {
    /**
     * 
     * @type {Terrain}
     * @memberof Tile
     */
    terrain?: Terrain;
    /**
     * 
     * @type {Feature}
     * @memberof Tile
     */
    feature?: Feature;
    /**
     * 
     * @type {Resource}
     * @memberof Tile
     */
    resource?: Resource;
    /**
     * 
     * @type {Improvement}
     * @memberof Tile
     */
    improvement?: Improvement;
    /**
     * 
     * @type {CityCenter | Campus | TheaterSquare | HolySite | Encampment | CommercialHub | Harbor | IndustrialZone | EntertainmentComplex | WaterPark | Aqueduct | Neighborhood | Canal | Dam | Aerodome | Spaceport | GovernmentPlaza | DiplomaticQuarter}
     * @memberof Tile
     */
    district?: CityCenter | Campus | TheaterSquare | HolySite | Encampment | CommercialHub | Harbor | IndustrialZone | EntertainmentComplex | WaterPark | Aqueduct | Neighborhood | Canal | Dam | Aerodome | Spaceport | GovernmentPlaza | DiplomaticQuarter;
}

export function TileFromJSON(json: any): Tile {
    return TileFromJSONTyped(json, false);
}

export function TileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'terrain': !exists(json, 'terrain') ? undefined : TerrainFromJSON(json['terrain']),
        'feature': !exists(json, 'feature') ? undefined : FeatureFromJSON(json['feature']),
        'resource': !exists(json, 'resource') ? undefined : ResourceFromJSON(json['resource']),
        'improvement': !exists(json, 'improvement') ? undefined : ImprovementFromJSON(json['improvement']),
        'district': !exists(json, 'district') ? undefined : CityCenter | Campus | TheaterSquare | HolySite | Encampment | CommercialHub | Harbor | IndustrialZone | EntertainmentComplex | WaterPark | Aqueduct | Neighborhood | Canal | Dam | Aerodome | Spaceport | GovernmentPlaza | DiplomaticQuarterFromJSON(json['district']),
    };
}

export function TileToJSON(value?: Tile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'terrain': TerrainToJSON(value.terrain),
        'feature': FeatureToJSON(value.feature),
        'resource': ResourceToJSON(value.resource),
        'improvement': ImprovementToJSON(value.improvement),
        'district': CityCenter | Campus | TheaterSquare | HolySite | Encampment | CommercialHub | Harbor | IndustrialZone | EntertainmentComplex | WaterPark | Aqueduct | Neighborhood | Canal | Dam | Aerodome | Spaceport | GovernmentPlaza | DiplomaticQuarterToJSON(value.district),
    };
}


