/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    District,
    DistrictFromJSON,
    DistrictFromJSONTyped,
    DistrictToJSON,
    WaterParkAllOf,
    WaterParkAllOfFromJSON,
    WaterParkAllOfFromJSONTyped,
    WaterParkAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface WaterPark
 */
export interface WaterPark extends District {
    /**
     * 
     * @type {Array<string>}
     * @memberof WaterPark
     */
    buildings?: Array<WaterParkBuildingsEnum>;
}

export function WaterParkFromJSON(json: any): WaterPark {
    return WaterParkFromJSONTyped(json, false);
}

export function WaterParkFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaterPark {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...DistrictFromJSONTyped(json, ignoreDiscriminator),
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function WaterParkToJSON(value?: WaterPark | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...DistrictToJSON(value),
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum WaterParkBuildingsEnum {
    FerrisWheel = 'ferris_wheel',
    Aquarium = 'aquarium',
    AquaticsCenter = 'aquatics_center'
}


