/* tslint:disable */
/* eslint-disable */
/**
 * Civ VI City Planner
 * Optomize your civ vi city plans
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaterParkAllOf
 */
export interface WaterParkAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof WaterParkAllOf
     */
    buildings?: Array<WaterParkAllOfBuildingsEnum>;
}

export function WaterParkAllOfFromJSON(json: any): WaterParkAllOf {
    return WaterParkAllOfFromJSONTyped(json, false);
}

export function WaterParkAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaterParkAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildings': !exists(json, 'buildings') ? undefined : json['buildings'],
    };
}

export function WaterParkAllOfToJSON(value?: WaterParkAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildings': value.buildings,
    };
}

/**
* @export
* @enum {string}
*/
export enum WaterParkAllOfBuildingsEnum {
    FerrisWheel = 'ferris_wheel',
    Aquarium = 'aquarium',
    AquaticsCenter = 'aquatics_center'
}


