from .bananas import Bananas
from .copper import Copper
from .cattle import Cattle
from .crabs import Crabs
from .deer import Deer
from .fish import Fish
from .maize import Maize
from .rice import Rice
from .sheep import Sheep
from .stone import Stone
from .wheat import Wheat
from .horses import Horses
from .iron import Iron
from .niter import Niter
from .coal import Coal
from .oil import Oil
from .aluminum import Aluminum
from .uranium import Uranium